name = "class-elliesbang"
compatibility_date = "2025-11-16"
main = "./functions/index.ts"

# Cloudflare Pages Functions
pages_build_output_dir = "./dist"

# ⚠️ D1 바인딩 없음
# ⚠️ ENV 없음
# → 전부 Cloudflare Dashboard에서 관리
