name = "class-web-app"
compatibility_date = "2024-10-01"

# Pages에서는 site 섹션 금지
# 대신 build.output_directory 사용

[build]
command = "npm run build"
output_directory = "app/dist"

[functions]
directory = "functions"